baseURL = 'https://ekremir.xyz'
languageCode = 'en-us'
title = "Ekrem Emir's blog"
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Ekrem Emir"
Content = "Here you can find information about me and projects I try to do. Contact links down below."

[[params.socialIcons]]
name = "Github"
url = "https://github.com/ekorekt"

[[params.socialIcons]]
name = "LinkedIn"
url = "<link2>"
